/** Русские подписи полей формы по имени ключа (имена ключей в конфиге одинаковы по смыслу). */
export const FIELD_LABELS: Record<string, string> = {
  // meta, currencies
  name: 'Название',
  seed: 'Seed случайности',
  artStyle: 'Стиль арта',
  hard: 'Хард-валюта',
  start: 'Стартовое значение',
  // energy
  max: 'Максимум',
  regen: 'Восстановление',
  amount: 'Количество',
  intervalSec: 'Интервал, с',
  allowOverMax: 'Награда может поднять выше максимума',
  // chains, generators
  id: 'ID',
  value: 'Ценность (формула от level)',
  levels: 'Уровни',
  energyCost: 'Стоимость энергии',
  cooldown: 'Кулдаун',
  charges: 'Предметов до кулдауна',
  seconds: 'Длительность кулдауна, с',
  produces: 'Что выдаёт',
  chain: 'Цепочка',
  level: 'Уровень',
  weight: 'Вес',
  // board
  width: 'Ширина',
  height: 'Высота',
  legend: 'Легенда раскладки',
  layout: 'Раскладка',
  locks: 'Замки',
  group: 'Группа',
  cells: 'Клетки [x, y]',
  content: 'Содержимое',
  item: 'Цепочка предмета',
  generator: 'Генератор',
  // levels
  ordersRequired: 'Нужно заказов',
  unlocks: 'Открывает группы замков',
  orderLevelCap: 'Потолок уровня в заказах',
  reward: 'Награда за уровень',
  // orders
  slots: 'Слотов заказов',
  refillDelaySec: 'Задержка пополнения, с',
  allowFromStorage: 'Сдавать из хранилища',
  fallbackTemplate: 'Запасной шаблон',
  reachability: 'Достижимость',
  mode: 'Режим',
  maxMergeDepth: 'Глубина слияния',
  countSources: 'Источники',
  onNoValidTemplate: 'Если шаблонов нет',
  templates: 'Шаблоны',
  boardLevels: 'Уровни доски [от, до]',
  maxRequirements: 'Максимум требований',
  requirements: 'Требования',
  levelRange: 'Диапазон уровней [от, до]',
  count: 'Количество',
  rewards: 'Награды',
  type: 'Тип',
  // bubbles
  spawnRules: 'Правила появления',
  source: 'Источник',
  chance: 'Вероятность (0–1)',
  lifetimeSec: 'Время жизни, с',
  onExpire: 'По истечении',
  everySec: 'Период, с',
  maxOnBoard: 'Максимум на доске',
  popCost: 'Стоимость лопания',
  currency: 'Валюта',
  formula: 'Формула',
  min: 'Минимум',
  // storage, itemActions
  enabled: 'Включено',
  returnToBoard: 'Возврат на доску',
  match: 'Шаблон (wood.2, wood.*, generator.id, *)',
  pickUp: 'Забрать',
  delete: 'Удалить',
  sell: 'Продажа',
  // cheats
  addHard: 'Добавить хард-валюту',
  refillEnergy: 'Восполнить энергию',
  skipLevel: 'Пройти уровень',
  skipTime: 'Сдвиг времени',
  minutes: 'Минуты',
  // telemetry
  counters: 'Счётчики',
  sources: 'Источники',
  energySpent: 'Трата энергии',
  total: 'Всего',
  byGenerator: 'По генераторам',
  // art
  chromaKey: 'Цвет фона (chroma key)',
  targetSizePx: 'Размер ассета, px',
  promptTemplate: 'Шаблон промпта',
  items: 'Переопределения по предметам',
  overrides: 'Свои картинки',
};

/** Вкладки формы — верхнеуровневые блоки конфига. */
export const BLOCK_LABELS: Record<string, string> = {
  meta: 'Общее',
  currencies: 'Валюта',
  energy: 'Энергия',
  chains: 'Цепочки',
  generators: 'Генераторы',
  board: 'Доска',
  levels: 'Уровни',
  orders: 'Заказы',
  bubbles: 'Пузыри',
  storage: 'Хранилище',
  itemActions: 'Действия',
  cheats: 'Читы',
  telemetry: 'Телеметрия',
  art: 'Арт',
};
